### ISSUE TITLE
Request: Dynamic Updates

### ISSUE THREAD

**Issue by aaronnoyes** [YS-Wong/Adaptive-Tab-Bar-Color#10]
It seems that this extension sets the color when the page loads, but it would be nice if there were an option to have it dynamically update as the view updates. A good example of this is how macOS Safari 15 handles content changes. 

To demonstrate, here is an example of Safari updating colors as a page changes compared to how this extension handles them using the website [ippsec.rocks](https://ippsec.rocks). On the initial page load, the page is a blue color which Adaptive-Tab-Bar-Color matches:
<img width="1432" alt="Screen Shot 2022-05-03 at 12 38 21 AM" src="https://user-images.githubusercontent.com/30840033/166409123-917e655d-28e2-469b-aaaa-32fe5c0615cd.png">

On this particular website, when you start typing in the main input, the page colors will change. Safari will dynamically change the tab bar color along with these changes, whereas Adaptive-Tab-Bar-Color keeps the original blue color from page load.

Safari:
<img width="1339" alt="Screen Shot 2022-05-03 at 12 38 05 AM" src="https://user-images.githubusercontent.com/30840033/166409285-5c8848e7-b9b6-4361-9785-ba2e93db9c87.png">
Firefox:
<img width="1432" alt="Screen Shot 2022-05-03 at 12 38 25 AM" src="https://user-images.githubusercontent.com/30840033/166409299-cfc889dd-0e03-4d9d-bd39-c49468cc66ca.png">

Would it be possible to mirror this behaviour using this extension and Firefox? I understand that it may come with a performance overhead it is possible, but it could be an experimental feature with a warning for those who are interested in using it.

**Comment by YS-Wong** [comment]
@aaronnoyes Thanks for your suggestion! Dynamic update should be very cool.

**Comment by YS-Wong** [comment]
@aaronnoyes I have added some dynamic updates feature, but it still can’t work on the website you mentioned. The CSS animation (color transition) is making it difficult.

**Comment by RaafatTurki** [comment]
@YS-Wong it's working but you have to invoke an input update after typing something (press enter or mouse click on the colored bg)

![image](https://user-images.githubusercontent.com/16624558/180316115-46d5df8a-9110-4628-b3c5-3ab5a2b50001.png)

**Comment by aaronnoyes** [comment]
@YS-Wong thank you so much for working on this!

**Comment by YS-Wong** [comment]
Hello, I tried making the add-on update tab bar color multiple times with some intervals, which solved the problem but caused another bug: switching tab shortly after tab bar color update starts could result in color applied to a wrong tab. It’s because different scripts run in an unsynchronized manner, timing is quite tricky.

Please leave the issue open. Maybe I’ll figure it out one day. Have a good one :)

**Comment by YS-Wong** [comment]
@aaronnoyes “Dynamic color update” got updated in latest release. Tab bar color will be refreshed after color transition. It’s still not perfect yet, so I might keep this issue opened.

**Comment by aaronnoyes** [comment]
@YS-Wong Thanks for keeping me updated and for your work!

**Comment by Phundrak** [comment]
Dynamic colour update doesn’t properly work for me on all websites, unfortunately. An example is [this website](https://docs.diesel.rs/2.0.x/diesel/index.html), you can change the theme by clicking on the cogwheel near the search bar. Another example is [my website alpha](https://alpha.phundrak.com/).

For the record, on my website, the theme changes when the attribute `color-scheme` on the `body` tag changes, as seen [in this file](https://labs.phundrak.com/phundrak/phundrak.com/src/commit/4da0c73e899a2488a44e54e8aef335dd1dd7908d/assets/main.scss#L19-L24) (and I just noticed the extensions picks a green colour instead of the correct background colour). I don’t know how the first website manages its own colour schemes, though.

**Comment by Phundrak** [comment]
Please disregard my previous comment, I just noticed the dynamic colour update is an option that has to be checked. Once I enabled it, it indeed works correctly. Maybe it could be made opt-out instead of opt-in?

**Comment by YS-Wong** [comment]
@Phundrak Regarding the latter website, you can open the add-on popup and click “Ignore theme color”. The add-on picked a green color because the website has defined its “theme color” in its HTML `<meta name="theme-color" content="#61972e">`.

**Comment by Phundrak** [comment]
That’s indeed it, thanks for the help!

**Comment by YS-Wong** [comment]
@Phundrak No worries. As the add-on gets more and more functions, maybe I shall make a small wiki/document.

**Comment by YS-Wong** [comment]
Although the “Dynamic Update” function will still be improved over time, this is not an “issue” any more.
