### ISSUE TITLE
Flashing theme after opening new window and resizing

### ISSUE THREAD

**Issue by 3YH** [YS-Wong/Adaptive-Tab-Bar-Color#11]
Here some more info and a video of the flashing theme issue after my review on the store.

Firefox Developer Edition
Version: 101.0b3
Build ID: 20220505190214
Addon options: Light mode, allow dark tab bar. 

Steps:
1. Open new tab with different theme (by drag or open in new tab)
2. Resize the newly opened window
3. Go back to tab with opposite theme

It stops instantly when I drag the new window back to the other window.
I can reproduce this every time on my build, sometimes it stops for a second, I think because of the lagg.

Please let me know if any more info is needed, thanks!

Video:
<a href="https://www.loom.com/share/6461d868980d4fa5a29694e2a7a8d0c8">
    <p>Popular shots on Dribbble — Firefox Developer Edition - 6 May 2022 - Watch Video</p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/6461d868980d4fa5a29694e2a7a8d0c8-with-play.gif">
  </a>

**Comment by YS-Wong** [comment]
@3YH 

Thanks for the screen record! This is a known issue, and it happens only with Firefox Developer Edition and Firefox Nightly: when the user opens two windows, one with dark tab bar and one with bright one, it keeps flashing. It’s because the APIs of Developer Edition and Nightly are slightly altered, and some codes doesn’t work on these versions.

I would recommend turning off “Allow dark/light tab bar” as a temporary fix.

**Comment by YS-Wong** [comment]
@3YH The “Follow System” option is dead with the new Firefox updates. Now add-on s can’t detect system color scheme anymore.
