### ISSUE TITLE
New tab issue

### ISSUE THREAD

**Issue by elliots2007** [YS-Wong/Adaptive-Tab-Bar-Color#15]
When opening a new tab, it is in light mode, instead of dark. Sometimes it even changes rapidly back and forth between them for a few seconds, before either changing to dark, or, in most cases, light mode.

Firefox Beta Edition
Version: 101.0b8
Build ID: 20220517185920
Add-on options: Dark mode, allow light tab bar.

Steps:
1. Open new tab
2. Observe
3. Retry (if it doesn't happen, I have observed it to happen quite randomly)

**Comment by YS-Wong** [comment]
@elliots2007 I actually never had the bug. Maybe you have installed conflicting add-ons.

**Comment by l0drex** [comment]
I have this issue on Google Maps. It not only switches the theme, but also the window moves and resizes and I see black areas inside the website - its really strange. It only happens when I allow a dark tab bar. I also tried setting a specific color for `google.com`, but it is ignored even if dynamic color update is turned of.

A solution that works for me is setting the `color-scheme` property to `system`
