### ISSUE TITLE
Too fast?

### ISSUE THREAD

**Issue by eboye** [YS-Wong/Adaptive-Tab-Bar-Color#3]
I really like the addon, but it's kinda too flashy for my taste :)

I'm not sure the dynamics behind, but consider this scenario:

1. When in dark mode, opening the website the has white background makes it burn my eyes. Maybe an option to not use the theme if HS(L) is over, let's say, 70%?
2. When clicking on a link with a redirect, eg. t.co ... it goes from dark to light to dark, so flashing. maybe some delay or something
3. It seems that there is no transition between colors. Maybe I'm wrong. But it would be great if it could be slower. For example 400-800ms for the transition to happen and with delay of 300ms.

Not sure if technically possible.

**Comment by YS-Wong** [comment]
@eboye

Thanks a lot for the suggestions! Now, there’s an option to prevent the tab bar being too bright. I think in that way it will work more systematically and consistently. Redirecting shall not cause flicking in theory, it needs more testing any way.

I’m not considering introducing color transition, because that would slow down the color switch and using more resources (not going to be a lot anyway). I want to make the add-on lite and simple.
