### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by AonDuine** [YS-Wong/Adaptive-Tab-Bar-Color#4]
With the new update, the extension stopped working as well as the previous version. 
For example, with Light theme  chosen will not adapt to almost any site, and with the dark theme in some sites with a light theme, like Twitter or youtube, the tabs are remaining dark

**Comment by YS-Wong** [comment]
@AonDuine That’s what it’s meant to work, for now. In v1.3.1 the two options “Light mode” and “Dark mode” are actually the previous “Force light mode” and “Force dark mode”. That’s because allowing the tab bar to turn bright from dark (or vice versa) causes problem when view websites with auto dark mode, e.g. developer.mozilla.org.

For instance, in the previous version, you got a bright tab bar on **Wikipedia**, and a dark one on **Twitch**. If you switch from **Wikipedia** to **developer.mozilla.org**, the website switches to light mode; if you switch from **Twitch** to **developer.mozilla.org**, it turns to dark mode again. That’s because Firefox detects color scheme by looking at the current tab bar theme (color of the text, I think), and websites with auto dark mode can easily get confused and be very flashy.

This is the issue I’m still struggling with: I can’t figure out how to override the color scheme (dark/light) of Firefox, without it keeps looking at the tab bar theme. For now, to prevent flashing, the only thing I can do is only giving “Force light mode” and “Force dark mode”, a.k.a “Light mode” and “Dark mode”. I’m thinking about giving back the options “Prefer light mode” and “Prefer dark mode” but marked as “experimental”.

Thank you for filing the issue. I’m still working on it.

**Comment by YS-Wong** [comment]
@AonDuine Solved the problem. Everything works again.
