### ISSUE TITLE
Automatic light/dark mode switching

### ISSUE THREAD

**Issue by ildiem** [YS-Wong/Adaptive-Tab-Bar-Color#6]
Hello!

I may be remembering wrong, but I recall at one point this extension would not affect the actual browser light/dark mode setting, but it seems that the extension now overrides this, and I have to choose between light mode or dark mode. If this was a feature, will it be returning soon, or if I'm remembering wrong, could you consider adding this feature in please?

For reference I'm running v. 1.3.3 of this addon on Firefox 99.0.1 on macOS 12.3.1; I have Dark Reader installed, but none of the conflicting addons listed on this addon's page, and as far as I can tell no other addons that affect browser theme.

Thanks!

**Comment by YS-Wong** [comment]
@ildiem Hello!

You’re right, since v1.3.3 the add-on overrides browser’s color scheme settings. I included this feature because the websites with auto dark mode, for example Twitch, always switch color scheme itself, when the user switches from a tab whose tab bar has an opposite color scheme. That’s because the browser’s color scheme is affected by tab bar theme, if it’s not overrode. To prevent websites from turning dark mode on/off itself, I think overriding the color scheme settings was the best solution.

I’m not sure how do you want the add-on to work. I’m guessing you want websites to turn on/off dark mode automatically, following the OS settings?

**Comment by Arecsu** [comment]
I would like the websites and extension to turn on-off dark mode following the OS. I have Dark Reader configured so it will switch based on the OS settings, which turns to dark at night hours. Would be cool if the extension has an option to follow the system color scheme as well!

**Comment by YS-Wong** [comment]
I looked into Firefox’s API, and I found out that letting the color scheme follow the OS settings is achievable. But I’m also considering what should the add-on do, when there’s no such settings in the OS (e.g. Windows 7).

**Comment by astroryan12** [comment]
It is working wonderfully so far! Thank you!
