### ISSUE TITLE
Endlessly re-applying theme

### ISSUE THREAD

**Issue by kiritokatklian** [YS-Wong/Adaptive-Tab-Bar-Color#8]
There's a bug where a theme is endlessly re-applied which leads to high CPU usage and slows down Firefox completely. It happens when going from dark theme to light theme, and vice versa.

**Steps (Dark mode)**
1. Enable "Allow light tab bar"
2. Select "Dark Mode"
3. Open a new private window and search for anything.

Google loads up with light theme the first time and that's when Firefox starts to flicker as the theme is re-applied endlessly.

**Steps (Light mode)**
1. Enable "Allow light tab bar"
3. Select "Light Mode"
4. Open a new private window.

Private window loads up with dark theme and same thing as before happens. Flickering (look at the edges of the browser), high CPU usage and sluggish browser.

**Comment by YS-Wong** [comment]
@kiritokatklian 

Sorry for causing any inconvenience, and thanks for reporting the bug. I’ve done some testing, but I still can’t reproduce the bug. I think the add-on is incompatible with the others you’ve installed, such as `Dark Mode Website Switcher` which can change the color scheme of web content, because I’m guessing this line is causing the flickering:
https://github.com/YS-Wong/Adaptive-Tab-Bar-Color/blob/80e0f6eb6b619903197e41e38686be100a6b3e78/background.js#L141

**Comment by kiritokatklian** [comment]
@YS-Wong

I don't use any other theming extensions, but I tried to disable all extensions I use and the issue keeps coming up. It happens whenever there are dark and light themed pages open at the same time while "Allow light/dark tab bar" is enabled.

I'm using Firefox on macOS 12.4 latest beta.

https://user-images.githubusercontent.com/6556281/166143047-f52af886-a176-44bb-9591-a9864481e38e.mp4

**Comment by YS-Wong** [comment]
@kiritokatklian 

Thanks for the screen record. I’m actively working on it.

**Comment by YS-Wong** [comment]
@kiritokatklian 

As a temporary solution, I would recommend you turning off “Allow dark/light tab bar” in the add-on’s preference page. I’m sorry that I still can’t figure out how to fix it.
