### ISSUE TITLE
Color changes only happen when the page loads

### ISSUE THREAD

**Issue by snthcy** [YS-Wong/Adaptive-Tab-Bar-Color#9]
Color changes only happen when the page loads, going to a different tab that's already loaded doesn't change the color.

Would it be possible to prioritize this addon so Firefox loads it as soon as the browser opens? There's seems to be some sort of delay

Another thing I noticed was that the place you actually type stays the same
![image](https://user-images.githubusercontent.com/47870580/166256892-85b9a07a-0ac1-4f06-a536-9c15ee723f80.png)

**Comment by YS-Wong** [comment]
@snthcy 

Thanks for reporting the bug.

In theory, the tab bar should change color when you switch tabs. I wonder if it always happens or just happens to specific URLs? If the tab bar never changes color when you switch tabs, make sure you haven’t installed any conflicting add-on. If it only bugs when you open a specific website, providing me with the URL will help a lot.

I’m not sure if you’re using Firefox Nightly, because the add-on bugs a lot with it, but I’m actively fixing it.

Small delay is expected. I’m also minimizing the delay, but I don’t think it can be avoided.

A lot of people want address bar coloring as well. I’m considering including the feature in future versions.

**Comment by snthcy** [comment]
Yeah, I am using Nightly.

**Comment by YS-Wong** [comment]
@snthcy 

Bug fixed. v1.4.6 should work fine now.

As you are using Firefox Nightly, this bug can happen: #11 

If that happens, I would recommend turning off “Allow dark/light tab bar”.
